---
# tasks file for sa_jupyterlab
  - name: Set installation facts for python3
    set_fact:
      jupyterhub_python_base_dir: /usr/local
      jupyterhub_python_interpreter: /usr/local/bin/python3
      jupyterhub_pip: /usr/local/bin/pip3
    when: jupyterhub_python == "python3"

  - name: Set installation facts for anaconda
    set_fact:
      jupyterhub_python_base_dir: "{{ anaconda_current_dir }}"
      jupyterhub_python_interpreter: "{{ anaconda_current_dir }}/bin/python"
      jupyterhub_pip: "{{ anaconda_current_dir }}/bin/pip"
    when: jupyterhub_python == "anaconda"

  - name: JupyterHub | create jupyter group
    group: name=jupyter state=present
    become: yes
    tags:
      - jupyterlab

  - name: JupyterHub | create jupyter user
    user: name=jupyter state=present groups=jupyter,shadow
    become: yes
    tags:
      - jupyterlab

  - name: Debug | ansible python version
    debug: var="ansible_python_version"

  - name: JupyterLab | install rustup for jupyter user
    shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    args:
      creates: "~/.cargo/bin/"
    become: yes
    become_user: jupyter
    tags:
      - jupyterlab
      - skip_ansible_lint

  - name: JupyterLab | install rustup for current user
    shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    args:
      creates: "~/.cargo/bin/"
    tags:
      - jupyterlab
      - skip_ansible_lint

  - name: JupyterLab | install rustup for root
    shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    args:
      creates: "~/.cargo/bin/"
    become: yes
    tags:
      - jupyterlab
      - skip_ansible_lint

  - include_tasks: tasks_git.yml
    when: option_install_git

  - include_tasks: tasks_python3.yml
    when: option_install_python3

  - include_tasks: tasks_py_anaconda.yml
    when: option_install_anaconda

  - include_tasks: tasks_nodejs.yml
    when: option_install_nodejs

  - include_tasks: tasks_jupyterlab.yml
