---
  # sa-git 1.1.0
  - name: GIT | Install modern git ppa repo
    ansible.builtin.apt_repository:
      repo: 'ppa:git-core/ppa'
    become: yes
    tags:
      - git

  - name: GIT | Install package
    ansible.builtin.apt:
      pkg: "git"
      state: present
      update_cache: yes
    become: yes
    tags:
      - git
