---
  #  sa-python-anaconda v 1.2.0
  - name: Anaconda | check for install
    ansible.builtin.command: "test -e {{ anaconda_current_dir }}/bin/conda"
    ignore_errors: true
    changed_when: False
    register: anaconda_installed
    tags:
      - anaconda

  - block:

    - name: Anaconda | get web install
      ansible.builtin.get_url:
        url: 'https://repo.continuum.io/archive/{{ anaconda_name }}.sh'
            # https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
        dest: /tmp/anaconda_installer.sh
        mode: 0755
      tags:
        - anaconda

    - name: Anaconda | execute web install
      ansible.builtin.command: "/tmp/anaconda_installer.sh -b -p {{ anaconda_install_dir }}"
      become: yes
      tags:
        - anaconda

    - name: Anaconda | Reset rights, group owner
      ansible.builtin.file: dest="{{ anaconda_install_dir }}" owner=root group="{{ anaconda_group | default('root') }}" recurse=yes
      become: yes
      tags:
        - anaconda

    - name: Anaconda | Reset rights, group write
      ansible.builtin.command: chmod -R g+w {{ anaconda_install_dir }}
      become: yes
      tags:
        - anaconda
        - skip_ansible_lint

    - name: Anaconda | Link current
      ansible.builtin.file: src="{{ anaconda_install_dir }}" dest="{{ anaconda_current_dir }}" state=link
      become: yes
      tags:
        - anaconda


    when: anaconda_installed is failed

  - name: Anaconda | Update packages
    ansible.builtin.command: "{{ anaconda_current_dir }}/bin/conda update -y --all"
    when: option_anaconda_update_packages
    become: yes
    tags:
      - anaconda

  - name: Ensure python3-distutils present
    ansible.builtin.command: "{{ anaconda_current_dir }}/bin/conda install -y -c anaconda setuptools"
    become: yes
    tags:
      - anaconda
      - skip_ansible_lint

  - name: Anaconda | add to profile
    ansible.builtin.template:
      src: "{{ role_dir }}/templates/anaconda_profile.sh.j2"
      dest: "/etc/profile.d/anaconda_profile.sh"
      mode: "0644"
    when:  option_anaconda_addtoprofile
    become: yes
    tags:
      - anaconda

  - name: Anaconda | install additional packages
    ansible.builtin.command: "{{ anaconda_conda_bin }} install -y -c {{ item }}"
    changed_when: not (conda_install_result.stdout | search('All requested packages already installed'))
    with_items: "{{ anaconda_additional_packages | default([]) }}"
    register: conda_install_result
